on:
  schedule:
    - cron: "0 1 * * 0"
  workflow_dispatch:

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@main
        id: latest_release
        with:
          latest: true
          repository: "damoun/sync-twitch-events"
          fileName: "sync-twitch-events_amd64"
          out-file-path: "."
      - run: chmod +x ./sync-twitch-events_amd64 && ./sync-twitch-events_amd64
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_BROADCASTER_ID: "29776980"
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_EVENT_LOCATION: https://twitch.tv/dam0un
          DISCORD_GUILD_ID: "306182341888442368"
