on:
  schedule:
    - cron: "0 1 * * 0"
  workflow_dispatch:

jobs:
  sync:
    name: sync
    runs-on: ubuntu-latest
    steps:
      - name: Download latest release
        uses: robinraju/release-downloader@v1.4
        id: release
        with:
          latest: true
          repository: "damoun/sync-twitch-events"
          fileName: "sync-twitch-events_v*_x86_64-unknown-linux-musl.tar.gz"
          out-file-path: "."
      - name: Extract release
        uses: ihiroky/extract-action@v1
        with:
          file_path: sync-twitch-events_${{ steps.release.outputs.release }}_x86_64-unknown-linux-musl.tar.gz
          extract_dir: .
      - run: ./sync-twitch-events
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET: ${{ secrets.TWITCH_CLIENT_SECRET }}
          TWITCH_BROADCASTER_ID: 29776980
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          DISCORD_EVENT_LOCATION: https://twitch.tv/dam0un
